import React, {Component} from 'react';
    class ServicesView extends Component {
        render(){
            return (
                <div>
                    <h1>Services</h1>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt faucibus diam, quis luctus neque consequat quis. Cras eget ligula et arcu egestas sagittis. Ut commodo purus id velit pretium sodales. Aenean eu rhoncus purus. Sed commodo lobortis velit, vitae cursus velit eleifend vitae. Sed sit amet scelerisque nunc. Ut bibendum velit at enim condimentum, viverra pulvinar felis sagittis. Pellentesque iaculis gravida massa, eget posuere ligula congue id. Nunc ut tincidunt enim. Praesent facilisis a lacus et sollicitudin. Fusce vitae consequat ligula. Phasellus facilisis ultricies libero, sit amet efficitur risus. Cras imperdiet congue metus.</p>

                    <p>Curabitur pretium, enim vitae consequat porttitor, felis dolor laoreet nulla, eu lobortis erat quam et urna. In hac habitasse platea dictumst. Pellentesque et dolor eu quam mollis mollis. Vestibulum mollis leo mi, id luctus risus sollicitudin vel. Etiam quis malesuada arcu. Morbi iaculis rutrum ante, non ullamcorper mauris maximus in. Nam id tincidunt tortor. Phasellus condimentum ex orci, vitae vestibulum lorem pharetra nec. Nullam molestie, nisi ac suscipit facilisis, nisl enim pellentesque diam, id vulputate ipsum neque sed ligula. Nunc facilisis malesuada quam, non faucibus diam efficitur non. Sed nec aliquet nulla. Ut bibendum posuere dapibus.</p>

                    <p>Etiam lorem nisi, consectetur ut rhoncus ut, cursus eu ligula. Aliquam sagittis libero risus, sed viverra arcu dictum id. Vestibulum tincidunt sed massa quis efficitur. Nullam eget felis maximus, suscipit arcu ut, fringilla dui. Donec quis lacus quis justo ullamcorper vulputate eu nec elit. Vestibulum at pellentesque ligula, quis feugiat urna. Donec eu aliquet felis. Aenean maximus dictum ullamcorper. Cras vel augue sit amet metus luctus dictum a semper mi. Fusce ut volutpat enim. Sed sed velit iaculis, sagittis tellus id, tempor enim. Vivamus sit amet eros semper, feugiat elit in, ornare mauris. Fusce laoreet, nisi non tincidunt maximus, ipsum lorem tempus diam, vehicula sodales ante tortor ac diam. Fusce vehicula, risus vel egestas aliquam, tortor augue vulputate elit, a fermentum odio enim sodales eros.</p>

                    <p>Phasellus commodo elit quis magna tempor, ut porttitor enim aliquam. Mauris vitae faucibus mauris, eget feugiat quam. Aenean luctus, augue ut tincidunt vehicula, mi enim lobortis nulla, eu vehicula nibh dolor non sem. Vivamus viverra, mauris sed aliquam ultrices, felis sapien tincidunt ligula, sit amet feugiat ipsum nibh ac turpis. Praesent semper interdum pretium. Quisque lacinia aliquam magna, quis consequat felis aliquet et. Morbi interdum lacus in scelerisque aliquam. Nulla facilisi. Pellentesque consectetur odio rutrum fringilla accumsan. Duis magna ante, venenatis a pulvinar nec, ornare a nunc.</p>

                    <img src="https://images.unsplash.com/photo-1517582837435-fdb3ccb5bb41?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=5b7b8b65ce4630bde2ede4e187393225&auto=format&fit=crop&w=1500&q=80" alt="image" />

                    <p>Mauris ex diam, dictum sed risus ac, egestas tempus lacus. Vestibulum sagittis orci quis venenatis tristique. Pellentesque at massa in quam placerat aliquet. In bibendum orci ut urna pharetra dictum. Aliquam erat volutpat. Vivamus euismod hendrerit euismod. Ut dictum nunc nec molestie molestie. Fusce laoreet mauris magna, at suscipit felis consequat at. Cras laoreet diam nunc, pretium blandit ex aliquet ut. In hac habitasse platea dictumst. Morbi sagittis libero nec purus eleifend, in convallis ligula tincidunt. Aenean semper ullamcorper sodales. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>

                    <p>Mauris non magna massa. Nunc pellentesque sapien ac ipsum mollis, eu congue felis ultricies. Duis eget nibh condimentum, molestie metus a, dapibus elit. Sed eget vulputate massa. Nullam laoreet massa sit amet dolor vestibulum scelerisque. Sed cursus scelerisque eros sit amet lacinia. Suspendisse quis tempor eros, eu convallis arcu. Phasellus ut felis nulla. Nam interdum suscipit ipsum, sed convallis enim gravida scelerisque. Praesent placerat, ex nec commodo malesuada, sem ex venenatis quam, vel aliquam turpis augue at ante. Quisque consectetur augue porttitor ipsum laoreet, eget mattis lorem tincidunt. Donec vestibulum justo a dui suscipit, quis tempor dui auctor. Aliquam vehicula auctor lorem quis vestibulum. Duis tincidunt eleifend dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis venenatis quis neque non mattis.</p>

                    <p>Maecenas a sapien consectetur, volutpat libero in, mattis felis. Donec sit amet sem leo. Aenean in condimentum sapien. Mauris porttitor facilisis placerat. Sed ac lectus eleifend nunc euismod cursus id et nunc. Vivamus nisl dolor, interdum eget lacus sit amet, porta cursus velit. In turpis erat, consectetur vitae lobortis eu, egestas ut magna. Ut lorem justo, hendrerit id tincidunt a, condimentum in nunc. Nullam sollicitudin dolor a rhoncus efficitur.</p>

                    <p>Curabitur neque dolor, suscipit vitae semper eu, facilisis faucibus ante. Phasellus efficitur lobortis pharetra. Etiam lacinia dolor non enim dictum ornare. Pellentesque in tempor magna, id euismod purus. Nulla consectetur neque fringilla odio interdum, vitae blandit nisl feugiat. Praesent vestibulum erat quis risus rhoncus tempor. Nullam vel purus gravida massa commodo iaculis. Curabitur tempus sagittis tellus, in convallis nulla faucibus a. Praesent aliquam, tortor ut mattis ullamcorper, turpis ante molestie mauris, nec venenatis tortor ligula eget massa. Maecenas at consequat nisl. Praesent pulvinar scelerisque accumsan. Quisque elementum facilisis nibh. Proin consequat eros ut tortor mollis, sed sollicitudin tortor convallis.</p>
                </div>
            );
        }
    }
    export default ServicesView;